title: Magic Green # capitalized for seo reasons!
subtitle: Sustainable and environment-friendly examples from Bali and beyond.
content_is_about: Going Green # general content of website, used in footer menu title
description: > # this means to ignore newlines until "baseurl:"
  Magic Green is a showcase of examples, infos and addresses of all stuff green related in Bali and beyond.
keywords: magazine, natural, nature-friendly, magic-green, sustainable business practises, environment-friendly, renewable-energy, low-impact, Bali, Indonesia, south east Asia, environment-conscious, wise, minimal impact, healthy, water purification techniques, communication platform, green news,
lang: en
version: 0.1.0


# site architecture
baseurl: ""
url: "https://magicgreen.org"
qr: show # 'show' or 'hide' put qr.svg in includes/defs.html call it: icn--qr
menu: long_menu # 'short_menu' or 'long_menu'
show_logo: show # 'show' or 'hide'
has_about_page: true # true or empty
has_term_page:  # true or empty

# client data
company:
  name: Magic Green
  legal_name: PT Gama Bali Dwipa #if need to overrides 'company.name' in footer fill up this one
  email: info@magicgreen.org
  telephone:
  fax:
  address: #
  maplink: #
  country: #
  twitter: #complete URL
  facebook_page: https://fb.me/magicgreen.org #complete URL
  youtube: #complete URL
  instagram: #complete URL
  linkedin: #complete URL
  tripadvisor: #complete URL
  booking: #complete URL
  airbnb: #complete URL
  gplus: #complete URL
  tumblr: #complete URL
  soundcloud: #complete URL



# SEO https://jekyll.github.io/jekyll-seo-tag/usage/
#
# SEO tag will use the YAML front matter if included in a post, page, or document:
#
# title
# description
# image - (e.g., /assets/page-pic.jpg)
# author - Page-specific author (see below)
# lang - Page-specific language

author: rokma
twitter:
  username: rokmatwit
facebook:
  app_id: #Facebook app ID for Facebook insights
  publisher: #Facebook page URL or ID of the publishing entity
  admins: #Facebook user ID for domain insights linked to a personal account
logo: /assets/favicons/apple-touch-icon-152x152.png
webmaster_verifications:
  google: google32e66f1a5601ec40

google:
  analytics: UA-119013410-1

# Build settings
markdown: kramdown
plugins:
 - jekyll/tagging
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
 - html-proofer
exclude:
  - Gemfile.lock
  - node_modules
  - package-lock.json
  - Gemfile

permalink: /:title/ # pretty


collections:
  pages:
    output: true
    permalink: /:title/

defaults:
  -
   scope:
     type: posts
   values:
     layout: post # change this to get the layout needed
     permalink: /:categories/:title/

tag_page_layout: post_index_tag
tag_page_dir: ./
tag_permalink_style: pretty


## NOTES:
## 'category': must be singular/plural and match the dir name in both assets and pages. Used in urls too.
## title: it's used in headings only to get the plural as in 'tours'.
## photos must be named same as 'page.title' and when more than 1 '{{page.title}}-02' and so on.

# posts/subjects data


offer:
  post_type_01: services #(garbage recycle, e-bikes rental... )
  post_type_02: products #(, electric bikes, bamboo straws, paper bags, water purifiers, bamboo frame pushbikes,solar panels, solar water-heaters...)
  post_type_03: techniques #(purification, energy efficiency...)
  post_type_04: resources #(consulting companies, NGOs...)
  post_type_05: solutions #(green roofs, green walls... )
  post_type_06: tips #(grow healthy food, say no to plastic, buy wrap less products...)
  post_type_07: know #(plants properties, natural medicines, healthy living, yoga, diet, superfoods)
